### ISSUE TITLE
How is async handled

### ISSUE THREAD

**Issue by basarat** [TypeStrong/typescript-project-services#3]
Specifically how do you get `createLanguageService` (https://github.com/TypeStrong/typescript-project-services/blob/186c4bec51c72d7238919137e04ecb605abe3d9f/src/main/project.ts#L473-L474) to execute in a non UI thread. @fdecampredon I suspect its handled by `brackets` and the code is not in this project. But I might be wrong. 

Alternatively you might be calling `createLanguageService` with a language service host that doesn't have `getScriptFileNames` populated and then populating them lazily.

**Comment by fdecampredon** [comment]
Basically my solution is to have tsps running entirely in a webworker. 
Like you have guessed having a languageServiceHost completely synchronous is a big problem currently the solution I have is to get **all** the fileNames in the current dir, and doing globing/selection inside the project, I would prefer a different solution but :X I didn't find one.
I'll try to make a readme this evening so you can understand the project better.

**Comment by basarat** [comment]
Cool. This question is pretty much answered. Thanks!
